[db]
driver  = "mysql"
connstr = "root:tester@tcp(127.0.0.1:3306)/copyright?charset=utf8"
[eth]
connstr = "http://localhost:8545"
keydir = "../../../data/keystore"
fundation = "0x9aebc666e7f870c88beba4c0762dca8b583c26fc"
pxaaddr = "0x61bb16e1a0b53859a0d61f3bbf4d1a09753e1655"
pxcaddr = "0xaACda0F05c76D13855DCA8b130b2CE6aF7cb515b"
fundationPWD = "eilinge"