[db]
driver  = "mysql"
connstr = "root:tester@tcp(127.0.0.1:3306)/copyright?charset=utf8"
[eth]
connstr = "http://localhost:8545"
keydir = "../../../data/keystore"
fundation = "0x9aebc666e7f870c88beba4c0762dca8b583c26fc"
pxaaddr = "0x02cc9125960528bb0d9584ed9ffbe4f0d336ed7b"
pxcaddr = "0x6944694Db7325C5BE6b27eac98B095FcF8572eCD"
fundationPWD = "eilinge"